### ISSUE TITLE
Asking for the checkpoint of AE model

### ISSUE THREAD

**Issue by tryhiseyyysum** [neu-vi/MARDM#1]
Hi, I have not found the checkpoint of AE model, you might forget to upload it. Could you give another google drive address that containing the checkpoint of AE model?

**Comment by cr8br0ze** [comment]
Thank you for the reminder. I just realized I forgot to provide the pre-trained AE link. I will update the README.md and you can also download using the following command:
```bash
gdown --fuzzy https://drive.google.com/file/d/1nfX_j8VzMmynqKv8x68pXrsL3c0qWLXA/view?usp=sharing
```
Thank you :)

**Comment by cr8br0ze** [comment]
Thank you for the reminder. I just realized I forgot to provide the pre-trained AE link. I will update the README.md and you can also download using the following command:
```bash
gdown --fuzzy https://drive.google.com/file/d/1nfX_j8VzMmynqKv8x68pXrsL3c0qWLXA/view?usp=sharing
```
Thank you :)
